# Generated by Django 3.0.5 on 2020-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='None', max_length=50)),
                ('user_sex', models.CharField(default='None', max_length=10)),
                ('user_birth', models.CharField(default='None', max_length=50)),
                ('user_password', models.CharField(default='None', max_length=50)),
            ],
        ),
    ]
