# Generated by Django 3.0.5 on 2020-09-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_users_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favor_movie',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
